Refactor ROS2 CI workflow for improved clarity

diff --git a/.github/workflows/ros2_ci.yml b/.github/workflows/ros2_ci.yml
--- a/.github/workflows/ros2_ci.yml
+++ b/.github/workflows/ros2_ci.yml
@@ -26,37 +26,45 @@ jobs:
       image: ros:${{ matrix.rosdistro }}-ros-base
 
     steps:
-      - name: Setup directories
-        run: mkdir -p ros2_ws/src
+      - name: Check out repository
+        uses: actions/checkout@v4
 
-      - name: Remove CodeQL duplicated source roots
+      - name: Setup ROS2 workspace
         run: |
-          find ros2_ws -type d -name '_codeql_detected_source_root' -prune -exec rm -rf '{}' +
+          mkdir -p /ros2_ws/src
+          ln -s $GITHUB_WORKSPACE /ros2_ws/src/core2026
 
       - name: Install dependencies
         run: |
-          apt-get update
-          rosdep update
-          rosdep install --from-paths ros2_ws/src/${{ github.event.repository.name }} \
-            --ignore-src -r -y --rosdistro ${{ matrix.rosdistro }}
+          apt-get update &&
+          rosdep update &&
+          rosdep install --from-paths /ros2_ws/src -i -y --rosdistro ${{ matrix.rosdistro }}
 
       - name: Install diagnostic-updater
-        run: |
-          apt-get update
-          apt-get install -y ros-${{ matrix.rosdistro }}-diagnostic-updater
+        run: apt-get install -y ros-${{ matrix.rosdistro }}-diagnostic-updater
 
       - name: Build tests
         id: build_test
         run: |
-          . /opt/ros/${{ matrix.rosdistro }}/setup.sh
-          colcon build --base-paths ros2_ws/src
+          . /opt/ros/${{ matrix.rosdistro }}/setup.sh &&
+          cd /ros2_ws &&
+          colcon build
         continue-on-error: true
+
+      - name: build_test command success
+        if: steps.build_test.outcome == 'success'
+        run: echo "result - success"
+
+      - name: build_test command failure
+        if: steps.build_test.outcome == 'failure'
+        run: echo "result - failure" && exit 1
 
       - name: Run tests
         id: run_test
         run: |
-          . /opt/ros/${{ matrix.rosdistro }}/setup.sh
-          colcon test --base-paths ros2_ws/src
+          . /opt/ros/${{ matrix.rosdistro }}/setup.sh &&
+          cd /ros2_ws &&
+          colcon test &&
           colcon test-result --verbose
         continue-on-error: true
 
